sudo: required
services:
    - docker
before_install:
    - docker build -t bhagath/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true bhagath/docker-react npm run test

language: generic 